# setup

In [2]:
import torch
from transformers import *

import pandas as pd

HOME='/Users/yang.zhang/git/recsys20/'
p_in=f'{HOME}/data'

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

    (rcss20) ➜  recsys20 git:(master) ✗ wc -l data/training.tsv
     148,075,238 data/training.tsv
    (rcss20) ➜  recsys20 git:(master) ✗ wc -l data/val.tsv
     151,27,684 data/val.tsv

# training.tsv

In [3]:
cols=[
'Tweet Features: Text tokens',
'Tweet Features: Hashtags',
'Tweet Features: Tweet id',
'Tweet Features: Present media',
'Tweet Features: Present links',
'Tweet Features: Present domains',
'Tweet Features: Tweet type',
'Tweet Features: Language',
'Tweet Features: Timestamp',
    
'Engaged With User Features: User id',
'Engaged With User Features: Follower count',
'Engaged With User Features: Following count',
'Engaged With User Features: Is verified?',
'Engaged With User Features: Account creation time',
    
'Engaging User Features: User id',
'Engaging User Features: Follower count',
'Engaging User Features: Following count',
'Engaging User Features: Is verified?',
'Engaging User Features: Account creation time',
    
'Engagement Features: Engagee follows engager?',
'Engagement Features: Reply engagement timestamp',
'Engagement Features: Retweet engagement timestamp',
'Engagement Features: Retweet with comment engagement timestamp',
'Engagement Features: Like engagement timestamp',
]
cols_val=cols[:-4]
cols_time=[
'Tweet Features: Timestamp',
'Engaged With User Features: Account creation time',
'Engaging User Features: Account creation time',
'Engagement Features: Reply engagement timestamp',
'Engagement Features: Retweet engagement timestamp',
'Engagement Features: Retweet with comment engagement timestamp',
'Engagement Features: Like engagement timestamp',
]

In [12]:
%%time
df=pd.read_csv(f'{p_in}/training.tsv',
               sep='\x01',
               header=None,
#                nrows=5000000,
               usecols=range(1,len(cols)),
               names=cols[1:],)

KeyboardInterrupt:

In [10]:
5000

50

In [246]:
for col in cols_time:
    df[col]=pd.to_datetime(df[col]*1e9)

In [5]:
df.head()

,Tweet Features: Hashtags,Tweet Features: Tweet id,Tweet Features: Present media,Tweet Features: Present links,Tweet Features: Present domains,Tweet Features: Tweet type,Tweet Features: Language,Tweet Features: Timestamp,Engaged With User Features: User id,Engaged With User Features: Follower count,...,Engaging User Features: User id,Engaging User Features: Follower count,Engaging User Features: Following count,Engaging User Features: Is verified?,Engaging User Features: Account creation time,Engagement Features: Engagee follows engager?,Engagement Features: Reply engagement timestamp,Engagement Features: Retweet engagement timestamp,Engagement Features: Retweet with comment engagement timestamp,Engagement Features: Like engagement timestamp
0,NaN,D4D1EBDE74F74C5DA529959AF979625C,NaN,NaN,NaN,TopLevel,22C448FF81263D4BAF2A176145EE9EAD,1581258144,D7EFC6D19CFB09B9A1CE4C4B0E0091F6,3517,...,0000006C3074607050F1339DDCB890BB,27428,600,False,1520948869,False,NaN,NaN,NaN,NaN
1,NaN,BFB529DAB6D384EB83E899A72AB3830D,Photo,NaN,NaN,TopLevel,B9175601E87101A984A50F8A62A1C374,1581018910,1F30A85E612A24B426013978ADB7AE46,39786,...,000005C520010F8917EEAB6F5B6EC1C4,17,77,False,1569692352,True,NaN,NaN,NaN,NaN
2,NaN,519078C7834E9642508F72A6C2D0F3B7,NaN,788ABAA22F1C4A9D186510C1E3E81F58,892B6E0BC037800B59112CFCB95E3301,TopLevel,22C448FF81263D4BAF2A176145EE9EAD,1581244866,9E1FD934C376903895DEEBCC0F6AB920,141726,...,000006829BEADA9EEA695CF0C334B426,2,29,False,1568107028,False,NaN,NaN,NaN,1.581247e+09
3,F0F2FBE57F08E7C4326682B5EDA63E3E\tE78674D32346...,52AAE9E33EFAC8C478C57B31A9E31ED1,NaN,C06B84A10A75AE4BF4A102AB45CC2ABF,C0F5328C1D36CD4B34D1808012E18D46,TopLevel,22C448FF81263D4BAF2A176145EE9EAD,1581250124,BEB3C337B266E2C4769065AD64724329,3044,...,000006829BEADA9EEA695CF0C334B426,3,30,False,1568107028,False,NaN,NaN,NaN,NaN
4,NaN,89C1298C55EB3D68E2784F0BFB69E6F8,NaN,NaN,NaN,TopLevel,22C448FF81263D4BAF2A176145EE9EAD,1580958805,9E1FD934C376903895DEEBCC0F6AB920,141370,...,000006829BEADA9EEA695CF0C334B426,3,30,False,1568107028,False,NaN,NaN,NaN,NaN

In [248]:
df['toks']=df['Tweet Features: Text tokens'].apply(lambda x: x.split('\t'))

In [249]:
df.toks[0]

['101',
 '6417',
 '3410',
 '3398',
 '3184',
 '1909',
 '56910',
 '16838',
 '82904',
 '1901',
 '100',
 '102']

In [250]:
" ".join(tokenizer.convert_ids_to_tokens(df.sample().toks.values[0]))

'[CLS] only ##ison essence [unused126] squeeze clifford dec [unused159] them them [unused109] [unused179] queen handling iraq defensive ##zed expansion 林 [UNK] good ##n 艹 spacious 森 responding [unused126] [unused115] [unused115] [unused183] [unused114] playwright [unused115] [UNK] ##ison utc fancy [UNK] marion bolivia [SEP]'

## val.tsv

In [251]:
dfval=pd.read_csv(f'{p_in}/val.tsv',
                  sep='\x01',
               header=None,
               nrows=50000,
               names=cols_val,)

In [252]:
dfval.shape

(50000, 20)

In [253]:
dfval

,Tweet Features: Text tokens,Tweet Features: Hashtags,Tweet Features: Tweet id,Tweet Features: Present media,Tweet Features: Present links,Tweet Features: Present domains,Tweet Features: Tweet type,Tweet Features: Language,Tweet Features: Timestamp,Engaged With User Features: User id,Engaged With User Features: Follower count,Engaged With User Features: Following count,Engaged With User Features: Is verified?,Engaged With User Features: Account creation time,Engaging User Features: User id,Engaging User Features: Follower count,Engaging User Features: Following count,Engaging User Features: Is verified?,Engaging User Features: Account creation time,Engagement Features: Engagee follows engager?
0,101\t47185\t10157\t100986\t10343\t55422\t119\t...,NaN,7647B4E9DAF4C1D8973397DC2A04F3E3,Photo,NaN,NaN,TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,1581703126,8A9AB92B775C62C4AB60DF6773A01571,13941,1216,False,1448292186,0000006C3074607050F1339DDCB890BB,27448,600,False,1520948869,True
1,101\t6006\t5086\t1939\t7418\t3601\t6406\t1913\...,NaN,CCBFBA5AFE7EFC03102EA8D0F86C4208,Photo,NaN,NaN,TopLevel,22C448FF81263D4BAF2A176145EE9EAD,1581736431,187AC59639DA9A6F32F7CD118EDD58F7,476439,1478,False,1254447722,00000776B07587ECA9717BFC301F2D6E,102,659,False,1478011810,False
2,101\t56898\t137\t44851\t10317\t11490\t10112\t1...,NaN,E18C2DCFC5AF20C650A0FD94598E69B7,Video,NaN,NaN,Retweet,ECED8A16BE2A5E8871FD55F4842F16B1,1582061925,82626B53CB2AD3B469E4AE06EAA9D930,367,702,False,1518708926,00000860E80C67D8C46CE57C64DE9444,230,189,False,1541013180,True
3,101\t13497\t10437\t94005\t11161\t73632\t11067\...,NaN,26DC813FDF8546B757BB9141099F119E,NaN,D58137F9D688C88435FD64FBAEA82B97,E91CDEC8DC7ABF30592FA024616FF970,TopLevel,ECED8A16BE2A5E8871FD55F4842F16B1,1582110043,7AFE06FF54898A1E9C716F539831849E,278,1229,False,1243548061,00000865A1538142CDA5936B07FE4311,65,165,False,1452599043,True
4,101\t24781\t10152\t42041\t38268\t10301\t10798\...,NaN,30A33055566AAC9EB18734C4EAD11FE1,NaN,AEF0CC9FA7B389B9A2ADF1331F00B65B,42DD9E2D4B2C0B0A71E909A6049EC2C2,TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,1581860270,D240DACE38CA84965270C86D47D3BF40,24313527,121,True,1177506290,00000865A1538142CDA5936B07FE4311,64,164,False,1452599043,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,101\t56898\t137\t11859\t29389\t12257\t102121\t...,NaN,60E3DE63E31498D185326ACD409144F1,NaN,NaN,NaN,Retweet,D3164C7FBCF2565DDF915B1B3AEFB1DC,1581786108,17735BF539134FA02184E1471253D8CC,9704,403,False,1240840663,00D6EF9CA936A7988B38E86FD0AC036C,3044,4946,False,1236491256,False
49996,101\t146\t112\t10323\t12361\t11912\t10380\t131...,NaN,C7628195406D407A5D100E82F18E6C55,NaN,NaN,NaN,TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,1581628958,42826B0236CB5CA5E7C065EC90F413EB,103282,780,True,1261597001,00D6EF9CA936A7988B38E86FD0AC036C,3044,4948,False,1236491256,False
49997,101\t28381\t117\t19395\t28775\t10121\t34597\t1...,NaN,00A1085A53C928C884698481C5E78979,NaN,NaN,NaN,TopLevel,ECED8A16BE2A5E8871FD55F4842F16B1,1581849500,9B20893303B93BC016C54F8F6DA7BF0F,674601,0,True,1468326262,00D6F50C9EBA936B941A71BDDEF75421,967,205,False,1260561752,False
49998,101\t17160\t10135\t100\t10117\t28854\t100\t131...,NaN,E43563E8A3E4BC701C1CCBEE345EF9F3,NaN,6BFFACB6A63DCE13ACD6E7A7E7A5CAD3,42DD9E2D4B2C0B0A71E909A6049EC2C2,TopLevel,D3164C7FBCF2565DDF915B1B3AEFB1DC,1581770033,D240DACE38CA84965270C86D47D3BF40,24311382,121,True,1177506290,00D6F50C9EBA936B941A71BDDEF75421,966,205,False,1260561752,False
49999,101\t6104\t2534\t100\t119\t7431\t1906\t5407\t2...,5AE8FB4252167C8ECEF241AB0D37B62E\tB2FD9EA3DE90...,56B202CDDD8F1E565BD69725DE4B9056,Photo,NaN,NaN,TopLevel,22C448FF81263D4BAF2A176145EE9EAD,1581776060,9FF178869423165CB24C80E56950AF9B,75,151,False,1513251388,00D6F89F6CEF8AE75DC9D14A13300833,26,63,False,1524234929,True